In [ ]:
import pandas as pd

In [ ]:
#파일들로부터 데이터 읽어오기
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
레모네이드 = pd.read_csv(파일경로)

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스톤 = pd.read_csv(파일경로)

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

In [ ]:
#데이터 모양으로 확인하기
print(레모네이드.shape)
print(보스톤.shape)
print(아이리스.shape)

(6, 2)
(506, 14)
(150, 5)

In [ ]:
# 칼럼 이름 출력
print(레모네이드.columns)
print(보스톤.columns)
print(아이리스.columns)

Index(['온도', '판매량'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')

In [ ]:
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)

독립 = 보스톤[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스톤[['medv']]
print(독립.shape, 종속.shape)

독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종']]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)
(506, 13) (506, 1)
(150, 4) (150, 1)

In [ ]:
레모네이드.head()

   온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [ ]:
보스톤.head()

      crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [ ]:
아이리스.head()

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
#라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
#데이터 사용
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
데이터 = pd.read_csv(파일경로)
데이터.head()

   온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [ ]:
#종속변수, 독립변수
독립 = 데이터[['온도']]
종속 = 데이터[['판매량']]
print(독립.shape, 종속.shape)#확인해보기

(6, 1) (6, 1)

In [ ]:
#모델을 만들기
X = tf.keras.layers.Input(shape=[1]) #1은 독립변수의 개수
Y = tf.keras.layers.Dense(1)(X) #1은 종속변수의 개수
model = tf.keras.models.Model(X, Y) #모델 완성
model.compile(loss='mse')#모델이 학습할 방법 정의

In [ ]:
#모델을 학습
model.fit(독립, 종속, epochs=10) #epochs에는 몇번을 학습시킬지 횟수

Epoch 1/10
1/1 [==============================] - 0s 4ms/step - loss: 1.4682e-04
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 1.4681e-04
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 1.4668e-04
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 1.4656e-04
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 1.4661e-04
Epoch 6/10
1/1 [==============================] - 0s 8ms/step - loss: 1.4668e-04
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 1.4673e-04
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 1.4669e-04
Epoch 9/10
1/1 [==============================] - 0s 7ms/step - loss: 1.4670e-04
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 1.4673e-04

In [ ]:
#모델을 이용